# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 0d55e92b160d03e53e9bad170eaf177d87ea37470cba4013d49040f8f79c5bf5365f5e369ab9557b640ca936046621c83bd4ede89b976715bf0d626b2af992fe

test:
  secret_key_base: c92c4290ad00e5957093c8a4ca157fa4bd528e5b3c84ec786f819ed6516ad9c458ecbafd9f820a74eb4629a025d772202392d9ff6e4dcfa372c8c0a57bd63ee5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
